/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author Arthur18
 */
public class ControladorP5 extends javax.swing.JFrame {

    
    private static ControladorP5 instance = null;
    private Treasure tesoro;
    private ArrayList<Treasure> todosLosTesoros=new ArrayList();
    private ArrayList<BadConsequence> todosLosBC=new ArrayList();
    
    public static ControladorP5 getInstance()
    {
        if(instance==null)
        {
            instance= new ControladorP5();            
        }
        
        return instance;          
    
    }
    
    public void setControladorP5(ControladorP5 controlador){
    
        instance=controlador;
        this.repaint();
        
        
    
    }
    
    private void fillTreasurePanel(JPanel aPanel, Treasure tesoro) {
        
                
                   TreasureView aTreasureView = new TreasureView();
                   aTreasureView.setTreasure (tesoro);
                   aTreasureView.setVisible (true);
                   aPanel.add (aTreasureView);
                
                // Se fuerza la actualización visual del panel
                aPanel.repaint();
                aPanel.revalidate();
    }
    
    private void fillBCPanel(JPanel aPanel, BadConsequence bc) {
        
                
                   PendingBadConsequenceView bcView = new PendingBadConsequenceView();
                   bcView.setPendingBadConsequence (bc);
                   bcView.setVisible (true);
                   aPanel.add (bcView);
                
                // Se fuerza la actualización visual del panel
                aPanel.repaint();
                aPanel.revalidate();
    }
    
    
    private void fillBCAdjustPanel(JPanel aPanel, BadConsequence bc) {
        
                
                   PendingBadConsequenceView bcView = new PendingBadConsequenceView();
                   bcView.setPendingBadConsequence (bc);
                   bcView.setVisible (true);
                   aPanel.add (bcView);
                
                // Se fuerza la actualización visual del panel
                aPanel.repaint();
                aPanel.revalidate();
    }
    /**
     * Creates new form ControladorP5
     */
    public ControladorP5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        identificacion = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        misTesoros = new javax.swing.JPanel();
        addOneHand = new javax.swing.JToggleButton();
        addBothHands = new javax.swing.JButton();
        addHelmet = new javax.swing.JButton();
        addShoes = new javax.swing.JButton();
        addArmor = new javax.swing.JButton();
        malosRollos = new javax.swing.JPanel();
        deathBC = new javax.swing.JButton();
        numericBC = new javax.swing.JButton();
        specificBC = new javax.swing.JButton();
        reajustados = new javax.swing.JPanel();
        adjustToFit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        identificacion.setText("Identificación");
        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });

        ID.setEditable(false);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        misTesoros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addOneHand.setText("Add OneHand");
        addOneHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneHandActionPerformed(evt);
            }
        });

        addBothHands.setText("Add BothHands");
        addBothHands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBothHandsActionPerformed(evt);
            }
        });

        addHelmet.setText("Add Helmet");
        addHelmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHelmetActionPerformed(evt);
            }
        });

        addShoes.setText("Add Shoes");
        addShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShoesActionPerformed(evt);
            }
        });

        addArmor.setText("Add Armor");
        addArmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArmorActionPerformed(evt);
            }
        });

        malosRollos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deathBC.setText("Death BC");
        deathBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathBCActionPerformed(evt);
            }
        });

        numericBC.setText("Numeric BC");
        numericBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numericBCActionPerformed(evt);
            }
        });

        specificBC.setText("Specific BC");
        specificBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificBCActionPerformed(evt);
            }
        });

        reajustados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        adjustToFit.setText("Reajustar");
        adjustToFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustToFitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reajustados, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(identificacion)
                        .addGap(54, 54, 54)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addOneHand, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(addBothHands)
                                .addGap(38, 38, 38)
                                .addComponent(addHelmet, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(addShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(addArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(misTesoros, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malosRollos, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(88, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(deathBC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(numericBC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(specificBC, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(adjustToFit, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(identificacion)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(misTesoros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOneHand)
                    .addComponent(addBothHands)
                    .addComponent(addHelmet)
                    .addComponent(addShoes)
                    .addComponent(addArmor))
                .addGap(64, 64, 64)
                .addComponent(malosRollos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deathBC)
                    .addComponent(numericBC)
                    .addComponent(specificBC))
                .addGap(18, 18, 18)
                .addComponent(reajustados, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adjustToFit)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        this.ID.setVisible(true);
        String identif="Arthur M. Rodriguez N " + "Y1680851W";
        this.ID.setText(identif);
        repaint();
    }//GEN-LAST:event_identificacionActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        
    }//GEN-LAST:event_IDActionPerformed

    private void addOneHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneHandActionPerformed
        tesoro=new Treasure("T",1,TreasureKind.ONEHAND);
        todosLosTesoros.add(tesoro);
        this.fillTreasurePanel(misTesoros,tesoro);
        repaint();
    }//GEN-LAST:event_addOneHandActionPerformed

    private void addBothHandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBothHandsActionPerformed
        tesoro=new Treasure("T",1,TreasureKind.BOTHHANDS);
        todosLosTesoros.add(tesoro);
        this.fillTreasurePanel(misTesoros,tesoro);
        repaint();
    }//GEN-LAST:event_addBothHandsActionPerformed

    private void addHelmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHelmetActionPerformed
        tesoro=new Treasure("T",1,TreasureKind.HELMET);
        todosLosTesoros.add(tesoro);
        this.fillTreasurePanel(misTesoros,tesoro);
        repaint();
    }//GEN-LAST:event_addHelmetActionPerformed

    private void addShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShoesActionPerformed
        tesoro=new Treasure("T",1,TreasureKind.SHOES);
        todosLosTesoros.add(tesoro);
        this.fillTreasurePanel(misTesoros,tesoro);
        repaint();
    }//GEN-LAST:event_addShoesActionPerformed

    private void addArmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArmorActionPerformed
        tesoro=new Treasure("T",1,TreasureKind.ARMOR);
        todosLosTesoros.add(tesoro);
        this.fillTreasurePanel(misTesoros,tesoro);
        repaint();
    }//GEN-LAST:event_addArmorActionPerformed

    private void deathBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathBCActionPerformed
        DeathBadConsequence malro= new DeathBadConsequence("BC",true);
        this.todosLosBC.add(malro);
        this.fillBCPanel(malosRollos,malro);
        repaint();
        
    }//GEN-LAST:event_deathBCActionPerformed

    private void numericBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numericBCActionPerformed
        NumericBadConsequence malro= new NumericBadConsequence("BC",1,2,3);
        this.todosLosBC.add(malro);
        this.fillBCPanel(malosRollos,malro);
        repaint();
    }//GEN-LAST:event_numericBCActionPerformed

    private void specificBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificBCActionPerformed
        
        Random alea = new Random();
        SpecificBadConsequence malro;
        int random;
        random=alea.nextInt(2)+1;
        
        if(random==1)
            malro= new SpecificBadConsequence("BC",1,new ArrayList(Arrays.asList(TreasureKind.HELMET,TreasureKind.ARMOR)),new ArrayList());
        else
            malro= new SpecificBadConsequence("BC",1,
            new ArrayList(Arrays.asList(TreasureKind.ONEHAND,TreasureKind.ONEHAND)),new ArrayList(Arrays.asList(TreasureKind.SHOES)));
        
        
        this.todosLosBC.add(malro);
        this.fillBCPanel(malosRollos,malro);
        repaint();
    }//GEN-LAST:event_specificBCActionPerformed

    private void adjustToFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustToFitActionPerformed
        for(BadConsequence bc: todosLosBC){
            
            BadConsequence malro= bc.adjustToFitTreasureLists(new ArrayList(), todosLosTesoros);
            this.fillBCAdjustPanel(reajustados, malro);
            
        }
        
        repaint();
            
    }//GEN-LAST:event_adjustToFitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControladorP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControladorP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControladorP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControladorP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControladorP5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton addArmor;
    private javax.swing.JButton addBothHands;
    private javax.swing.JButton addHelmet;
    private javax.swing.JToggleButton addOneHand;
    private javax.swing.JButton addShoes;
    private javax.swing.JButton adjustToFit;
    private javax.swing.JButton deathBC;
    private javax.swing.JButton exit;
    private javax.swing.JButton identificacion;
    private javax.swing.JPanel malosRollos;
    private javax.swing.JPanel misTesoros;
    private javax.swing.JButton numericBC;
    private javax.swing.JPanel reajustados;
    private javax.swing.JButton specificBC;
    // End of variables declaration//GEN-END:variables
}
